#database:
#  default:
#    link:   "mysql:root:12345678@tcp(127.0.0.1:3306)/focus"
#    debug:  true
redis:
  default: #default
    address: fushisanlang.cn:6380
    db: 0
    pass: redis
  session: #session
    address: fushisanlang.cn:6380
    db: 1
    pass: redis
  config: #save config data
    address: fushisanlang.cn:6380
    db: 2
    pass: redis
  data: #save game data
    address: fushisanlang.cn:6380
    db: 3
    pass: redis
server: #server port
  address: 34567
status: #game status
  version: 0.0.1
  gamename: 飞升
logger:
  path: "/Users/fushisanlang/src/go/go/src/farm/log"
  level: "all"
  stdout: true
  logger1:
    path: "/Users/fushisanlang/src/go/go/src/farm/log/init"
    level: "all"
    stdout: true



